# Grafik untuk Dashboard Monitoring Produk di E-commerce

## Import Libraries

In [111]:
# ---- Import Libraries ----
import pandas as pd
import numpy as np
import geopandas as gpd
import plotly.express as px
import altair as alt
from babel.numbers import format_currency

## Load Data

In [112]:
df = pd.read_excel('Identifikasi-Brand-E-Commerce.xlsx')
df

,PRODUCT LINK,TITLE,PRICE,DISCOUNT,MARKETPLACE,SELLER URL,SELLER NAME,LOCATION,CATEGORY,SUB CATEGORY,...,RATING COUNT,BPOM NUMBER,SNI,HALAL,NO REG PRODUCT,DESCRIPTION,CRAWLER_AT,ASAL BRAND,Kategori,Keterangan
0,https://blibli.com/p/kira-vest-luaran-batik-vi...,Kira Vest Luaran Batik Viscose | titik moela,385000.0,NaN,Blibli,-,titik moela,Kota Tangerang,Pakaian Pria,Jas Formal,...,NaN,-,-,-,-,?? Self-manufactured ?? Motif batik yang unik ...,2025-03-24,NaN,Fashion & Aksesoris,NaN
1,https://blibli.com/p/original-heatp-plester-pe...,Original HeatP Plester Pereda Nyeri Haid,19900.0,NaN,Blibli,-,Apt Ramah Sehati,Kota Jakarta Timur,Pakaian Wanita,Baju Hamil,...,NaN,-,-,-,-,<p></p>,2025-03-24,-,Perawatan Diri & Kesehatan,Alat Kesehatan
2,https://blibli.com/p/10pm-new-jacket-10pm-od-b...,10PM New Jacket 10Pm Od Blue 34015P2DB,449900.0,15.0,Blibli,-,Logo Jeans Official Store,Kota Bandung,Pakaian Pria,Hoodie & Sweatshirt,...,NaN,-,-,-,-,NaN,2025-03-24,-,Fashion & Aksesoris,NaN
3,https://blibli.com/p/180-degrees-hoodie-mounta...,180 Degrees HOODIE MOUNTAIN EVEREST BLACK Recy...,210000.0,NaN,Blibli,-,180 Degrees Official Store,Kab. Bandung,Pakaian Pria,"Jaket, Mantel, & Rompi",...,1.0,-,-,-,-,• Bahan 60% Fleece Recycle 40% Fleece \n<br>• ...,2025-03-24,-,Fashion & Aksesoris,NaN
4,https://blibli.com/p/2nd-red-jeans-celana-panj...,2nd RED Jeans Celana Panjang Denim Pria Legend...,459900.0,61.0,Blibli,-,2Nd RED Official Store,Kab. Bandung Barat,Pakaian Pria,NaN,...,2.0,-,-,-,-,• Long pant <br>• Warna Biru Muda <br>• Button...,2025-03-24,ID,Fashion & Aksesoris,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,https://blibli.com/p/zoya-hence-skirt-rok-polo...,Zoya HENCE Skirt - Rok Polos Wanita - Bahan Ma...,359000.0,20.0,Blibli,-,ZOYA Official Store,Kota Bandung,Pakaian Wanita,NaN,...,1.0,-,-,-,-,• Karakteristik kain dengan bahan tebal namun ...,2025-03-24,ID,Fashion & Aksesoris,NaN
2057,https://blibli.com/p/zuiter-basic-pants-celana...,ZUITER - Basic Pants | Celana bahan formal ker...,165000.0,10.0,Blibli,-,Zuiter Official Store,Kota Bekasi,Pakaian Pria,Jas Formal,...,NaN,-,-,-,-,NaN,2025-03-24,ID,Fashion & Aksesoris,NaN
2058,https://blibli.com/p/zweckout-denim-slim-fit-s...,ZWECKOUT Denim Slim Fit Stretch Biru Muda - Ce...,569000.0,72.0,Blibli,-,ZWECKOUT LABEL Official Store,Kab. Bandung,Pakaian Pria,NaN,...,NaN,-,-,-,-,• Kenyamanan Optimal: Bahan stretch memungkink...,2025-03-24,ID,Fashion & Aksesoris,NaN
2059,https://blibli.com/p/zwitsal-mini-travel-pack-...,Zwitsal Mini Travel Pack - Perawatan Kulit Bay...,62510.0,11.0,Blibli,-,Zwitsal Official Store,Kab. Bekasi,Pakaian Wanita,Kain,...,85.0,-,-,-,-,• Zwitsal Baby Natural Hair & Body [50 mL] \n<...,2025-03-24,NL,"Ibu, Bayi & Anak",Perawatan Kulit
2060,https://blibli.com/p/meja-tv-zyo-video-rack-so...,MEJA TV ZYO- VIDEO RACK SONOMA OAK- WHITE,1199000.0,63.0,Blibli,-,COURTS Official Store,Kota Bekasi,Pakaian Pria,Celana Panjang,...,1.0,-,-,-,-,• MEJA TV ZYO- VIDEO RACK SONOMA OAK- WHITE ha...,2025-03-24,ID,Rumah Tangga & Furniture,NaN

In [113]:
df.shape

(2061, 27)

In [114]:
gdf = gpd.read_file("idn_admbnda_adm1_bps_20200401.shp")

gdf.head()

,Shape_Leng,Shape_Area,ADM1_EN,ADM1_PCODE,ADM1_REF,ADM1ALT1EN,ADM1ALT2EN,ADM0_EN,ADM0_PCODE,date,validOn,validTo,geometry
0,27.367364,4.625437,Aceh,ID11,None,None,None,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((97.39178 2.03748, 97.39055 2.0..."
1,6.026648,0.458717,Bali,ID51,None,None,None,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((115.12509 -8.84761, 115.12499 ..."
2,9.279900,0.764911,Banten,ID36,None,None,None,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((105.54977 -6.99566, 105.55035 ..."
3,11.653771,1.630129,Bengkulu,ID17,None,None,None,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((102.38616 -5.47144, 102.38626 ..."
4,3.341561,0.260130,Daerah Istimewa Yogyakarta,ID34,None,None,None,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((110.8198 -8.20358, 110.81951 -..."

In [115]:
gdf2 = gpd.read_file("idn_admbnda_adm2_bps_20200401.shp")

gdf2.head()

,Shape_Leng,Shape_Area,ADM2_EN,ADM2_PCODE,ADM2_REF,ADM2ALT1EN,ADM2ALT2EN,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,validTo,geometry
0,2.360029,0.228968,Aceh Barat,ID1107,None,None,None,Aceh,ID11,Indonesia,ID,2019-12-20,2020-04-01,NaT,"POLYGON ((96.26836 4.768, 96.26822 4.7625, 96...."
1,1.963994,0.154136,Aceh Barat Daya,ID1112,None,None,None,Aceh,ID11,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((96.80559 3.71758, 96.80444 3.7..."
2,4.590182,0.236396,Aceh Besar,ID1108,None,None,None,Aceh,ID11,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((95.20544 5.28072, 95.20563 5.2..."
3,3.287754,0.316161,Aceh Jaya,ID1116,None,None,None,Aceh,ID11,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((95.58431 4.61495, 95.58379 4.6..."
4,4.448584,0.343038,Aceh Selatan,ID1103,None,None,None,Aceh,ID11,Indonesia,ID,2019-12-20,2020-04-01,NaT,"MULTIPOLYGON (((97.59461 2.80777, 97.59365 2.8..."

## Data Cleaning

In [116]:
# Mengubah lokasi berdasarkan kabupaten/kota ke lokasi berdasarkan provinsi
def normalize_lokasi(lokasi: str) -> str:
    lokasi = lokasi.strip()

    # Aturan khusus
    if lokasi == "Banjarbaru":
        return "Kota Banjar Baru"
    if lokasi == "Bekasi Kota":
        return "Kota Bekasi"
    if lokasi == "Kota Surakarta (Solo)":
        return "Kota Surakarta"
    if lokasi == "Solo":
        return "Kota Surakarta"

    # Aturan umum
    if lokasi.startswith("Kab."):
        lokasi = lokasi.replace("Kab.", "").strip()

    elif lokasi.startswith("Kota "):
        return lokasi

    elif lokasi.startswith("Jakarta"):
        return "Kota " + lokasi

    kota_spesial = [
        "Depok","Medan","Surabaya",
        "Yogyakarta","Tangerang Selatan","Cimahi",
        "Pekanbaru","Makassar","Manado",
        "Denpasar","Palembang","Palu",
        "Binjai","Salatiga","Banjar"
    ]
    if lokasi in kota_spesial:
        return "Kota " + lokasi

    return lokasi

df["DISTRICT"] = df["LOCATION"].apply(normalize_lokasi)

ref = gdf2[["ADM2_EN", "ADM1_EN"]].drop_duplicates()
ref = ref.rename(columns={"ADM2_EN": "DISTRICT", "ADM1_EN": "Provinsi"})

df = df.merge(ref, on="DISTRICT", how="left")

df = df.rename(columns={"Provinsi": "PROVINCE"})

In [117]:
selected_columns = [
    'PRODUCT LINK', 'TITLE', 'PRICE', 'MARKETPLACE', 'BRAND',
    'ASAL BRAND', 'Kategori', 'PROVINCE'
]

df = df[selected_columns]

df.head()

,PRODUCT LINK,TITLE,PRICE,MARKETPLACE,BRAND,ASAL BRAND,Kategori,PROVINCE
0,https://blibli.com/p/kira-vest-luaran-batik-vi...,Kira Vest Luaran Batik Viscose | titik moela,385000.0,Blibli,NaN,NaN,Fashion & Aksesoris,Banten
1,https://blibli.com/p/original-heatp-plester-pe...,Original HeatP Plester Pereda Nyeri Haid,19900.0,Blibli,100% PURE,-,Perawatan Diri & Kesehatan,Dki Jakarta
2,https://blibli.com/p/10pm-new-jacket-10pm-od-b...,10PM New Jacket 10Pm Od Blue 34015P2DB,449900.0,Blibli,10PM,-,Fashion & Aksesoris,Jawa Barat
3,https://blibli.com/p/180-degrees-hoodie-mounta...,180 Degrees HOODIE MOUNTAIN EVEREST BLACK Recy...,210000.0,Blibli,180 Degrees,-,Fashion & Aksesoris,Jawa Barat
4,https://blibli.com/p/2nd-red-jeans-celana-panj...,2nd RED Jeans Celana Panjang Denim Pria Legend...,459900.0,Blibli,2nd RED,ID,Fashion & Aksesoris,Jawa Barat

In [118]:
df.isnull().sum()

PRODUCT LINK    0
TITLE           0
PRICE           4
MARKETPLACE     0
BRAND           3
ASAL BRAND      1
Kategori        0
PROVINCE        0
dtype: int64

In [119]:
df = df.dropna()
df.isnull().sum()

PRODUCT LINK    0
TITLE           0
PRICE           0
MARKETPLACE     0
BRAND           0
ASAL BRAND      0
Kategori        0
PROVINCE        0
dtype: int64

In [120]:
df.duplicated().sum()

np.int64(1)

In [121]:
duplicate_rows = df[df.duplicated(keep=False)]
display(duplicate_rows)

,PRODUCT LINK,TITLE,PRICE,MARKETPLACE,BRAND,ASAL BRAND,Kategori,PROVINCE
546,https://blibli.com/p/elvicto-beach-club-parfum...,ELVICTO BEACH CLUB PARFUM 35ML,168000.0,Blibli,ELVICTO PERFUME,ID,Perawatan Diri & Kesehatan,Banten
547,https://blibli.com/p/elvicto-beach-club-parfum...,ELVICTO BEACH CLUB PARFUM 35ML,168000.0,Blibli,ELVICTO PERFUME,ID,Perawatan Diri & Kesehatan,Banten

In [122]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [123]:
df = df[df['ASAL BRAND'] != '-']
df.head()

,PRODUCT LINK,TITLE,PRICE,MARKETPLACE,BRAND,ASAL BRAND,Kategori,PROVINCE
4,https://blibli.com/p/2nd-red-jeans-celana-panj...,2nd RED Jeans Celana Panjang Denim Pria Legend...,459900.0,Blibli,2nd RED,ID,Fashion & Aksesoris,Jawa Barat
5,https://blibli.com/p/2nd-red-jeans-celana-panj...,2nd RED Jeans Celana Panjang Pria Slim Fit Jea...,459900.0,Blibli,2nd RED,ID,Fashion & Aksesoris,Jawa Barat
6,https://blibli.com/p/2xu-womens-aero-medium-im...,2XU Womens Aero Medium Impact Bra WR6347AMH|Sp...,1599000.0,Blibli,2XU,AU,Fashion & Aksesoris,Daerah Istimewa Yogyakarta
8,https://blibli.com/p/3h-overall-beatrice-mb/ps...,3H OVERALL BEATRICE MB,568000.0,Blibli,3H Clothing,ID,Fashion & Aksesoris,Dki Jakarta
9,https://blibli.com/p/post-it-3m-2059-aq-cpt-me...,Post It 3M 2059 AQ CPT Memo Tempel Sticky Note...,50000.0,Blibli,3M,US,Lain-Lain,Dki Jakarta

In [124]:
df.shape

(1583, 8)

In [125]:
df.to_excel('Identifikasi-Brand-E-Commerce (cleaned).xlsx', index=False)

In [126]:
# ---- Menghitung Rata-rata Geometrik ----
def gmean(values):
    arr = np.array(values)
    arr = arr[arr > 0]
    if len(arr) == 0:
        return 0
    return float(np.exp(np.mean(np.log(arr))))

# ---- Format angka jadi Rupiah ----
def fmt_rupiah(val):
    return format_currency(val, "IDR", locale="id_ID") if val else "–"

## Plots

### Donut chart

In [127]:
# Hitung jumlah produk lokal vs impor
lokal = df[df["ASAL BRAND"] == "ID"].shape[0]
impor = df[df["ASAL BRAND"] != "ID"].shape[0]

counts = pd.DataFrame({
    "Produk": ["Lokal", "Impor"],
    "Jumlah": [lokal, impor]
})
counts["Persentase"] = counts["Jumlah"] / counts["Jumlah"].sum()

# Warna custom
custom_colors = alt.Scale(
    domain=["Lokal", "Impor"],
    range=["#1f77b4", "#ff4b4b"]
)

# Selection interaktif (default pilih "Lokal")
selection = alt.selection_point(
    fields=["Produk"],
    value="Lokal",
    empty="none"
)

base = alt.Chart(counts).encode(
    theta=alt.Theta("Jumlah:Q", stack=True),
    color=alt.Color("Produk:N", scale=custom_colors),
    opacity=alt.condition(selection, alt.value(1), alt.value(0.5)),
    tooltip=[
        alt.Tooltip("Produk:N"),
        alt.Tooltip("Jumlah:Q"),
        alt.Tooltip("Persentase:Q", format=".1%")
    ]
).properties(height=280)

pie = base.mark_arc(innerRadius=72, outerRadius=130).add_selection(selection)

# Label tengah
text = alt.Chart(counts).mark_text(
    font="Lato",
    fontSize=30,
    fontWeight=700,
    fontStyle="italic"
).encode(
    text=alt.condition(
        selection,
        alt.Text("Persentase:Q", format=".1%"),
        alt.value("")
    ),
    color=alt.condition(
        selection,
        alt.Color("Produk:N", scale=custom_colors),
        alt.value("")
    )
).transform_filter(selection)

chart = pie + text
chart.display()

/tmp/ipython-input-1967379364.py:35: AltairDeprecationWarning:


Deprecated since `altair=5.0.0`. Use add_params instead.

alt.LayerChart(...)

### Bar chart

In [128]:
df = df[(df['Kategori'].apply(lambda x: isinstance(x, str))) & (df['ASAL BRAND'] == 'ID')]
kategori_counts = (
    df['Kategori']
    .value_counts()
    .reset_index(name='Jumlah Produk')
    .rename(columns={'index': 'Kategori'})
)

display(kategori_counts)

                     Kategori  Jumlah Produk
0         Fashion & Aksesoris            702
1            Ibu, Bayi & Anak            124
2    Rumah Tangga & Furniture            121
3  Perawatan Diri & Kesehatan             78
4      Hobi, Seni, & Olahraga             43
5            Otomotif & Mesin             30
6                   Lain-Lain             27
7         Elektronik & Gadget             11
8           Makanan & Minuman              5

### Grouped Bar Chart

In [129]:
# Buat kolom baru asal produk
df_grouped_bar = df.copy()
df_grouped_bar['Produk'] = df_grouped_bar['ASAL BRAND'].apply(
    lambda x: 'Lokal' if x == 'ID' else 'Impor'
)

# Filter hanya produk dengan label jelas
df_grouped_bar = df_grouped_bar[df_grouped_bar['Produk'].isin(['Lokal', 'Impor'])]

# Group by kategori & produk
grouped_price = (
    df_grouped_bar.groupby(['Kategori', 'Produk'])['PRICE']
    .agg(gmean)
    .reset_index()
    .rename(columns={'PRICE': 'Mean Price'})
)

# Chart bar rata-rata harga (grouped bar)
bar_chart = (
    alt.Chart(grouped_price)
    .mark_bar()
    .encode(
        x=alt.X("Kategori:N", title="Kategori", axis=alt.Axis(labelAngle=-45)),
        y=alt.Y("Mean Price:Q", title="Rata-rata Harga"),
        color=alt.Color("Produk:N",
                        scale=alt.Scale(domain=["Lokal", "Impor"],
                                        range=["#1f77b4", "#ff4b4b"]),
                        legend=alt.Legend(title="Produk")),
        xOffset="Produk:N",  # supaya grouped, bukan stacked
        tooltip=[
            alt.Tooltip("Kategori:N", title="Kategori"),
            alt.Tooltip("Produk:N", title="Produk"),
            alt.Tooltip("Mean Price:Q", title='Harga Rata-rata', format=',.2f')
        ]
    )
    .properties(
        width=700,
        height=450
    )
)

bar_chart.display()

alt.Chart(...)

### Analisis Harga Boxplot

In [130]:
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title='Distribusi Harga Produk Lokal vs Impor Semua Kategori',
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [131]:
kategori = "Elektronik & Gadget"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [132]:
kategori = "Fashion & Aksesoris"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [133]:
kategori = "Hobi, Seni, & Olahraga"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [134]:
kategori = "Ibu, Bayi & Anak"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [135]:
kategori = "Lain-Lain"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [136]:
kategori = "Makanan & Minuman"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [137]:
kategori = "Otomotif & Mesin"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [138]:
kategori = "Perawatan Diri & Kesehatan"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

In [139]:
kategori = "Rumah Tangga & Furniture"

# Buat kolom baru asal produk
df_box = df.copy()
df_box['Jenis Produk'] = df_box['ASAL BRAND'].apply(lambda x: 'Lokal' if x == 'ID' else 'Impor')

# Filter hanya produk dengan label jelas
df_box = df_box[df_box['Jenis Produk'].isin(['Lokal', 'Impor'])]

# Filter kategori (kecuali kalau pilih "Semua Kategori")
if kategori != "Semua Kategori":
    df_box = df_box[df_box["Kategori"] == kategori]

q95 = df_box["PRICE"].quantile(0.95)

# Buat boxplot
fig = px.box(
    df_box,
    x='Jenis Produk',
    y='PRICE',
    color='Jenis Produk',
    title=f'Distribusi Harga Produk Lokal vs Impor untuk Kategori {kategori}', # Update title dynamically
    color_discrete_map={'Lokal': '#1f77b4', 'Impor': '#ff4b4b'}
)

fig.update_layout(
    xaxis_title='Jenis Produk',
    yaxis_title='Harga Produk',
    yaxis_range = [0, q95 * 1.1],
    title_x=0.5,
    width=900,
    height=500
)

fig.show()

### Map choropleth

In [142]:
# simplify untuk kurangi kompleksitas poligon
gdf["geometry"] = gdf["geometry"].simplify(tolerance=0.01, preserve_topology=True)

# cache geojson supaya tidak dihitung ulang
geojson = gdf.__geo_interface__

# Hitung jumlah penjual produk lokal per provinsi
count = (
    df[df["ASAL BRAND"] == "ID"]
    .groupby("PROVINCE").size()
    .reset_index(name="count")
)

# Gabungkan dengan shapefile
merged = gdf.merge(count, left_on="ADM1_EN", right_on="PROVINCE", how="left")
merged["count"] = merged["count"].fillna(0)
merged["PROVINCE"] = merged["PROVINCE"].fillna(merged["ADM1_EN"])

# Define a default color theme
selected_color_theme = "Reds"

# Buat choropleth
fig = px.choropleth(
    merged,
    geojson=geojson,                # pakai cache geojson
    locations=merged.index,
    color="count",
    color_continuous_scale=selected_color_theme,
    hover_name="PROVINCE",
)

fig.update_traces(
    hovertemplate="<b>%{hovertext}</b><br>Jumlah Penjual: %{z}<extra></extra>"
)

# Fokus ke Indonesia
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}, height=500)

# Tampilkan chart
fig.show()

# Display category distribution for each province (as a table below the map)
display("Category Distribution per Province")
kategori_count_all = (
    df[df["ASAL BRAND"] == "ID"]
    .groupby(["PROVINCE", "Kategori"]).size().reset_index(name="Jumlah Produk")
    .sort_values(["PROVINCE", "Jumlah Produk"], ascending=[True, False])
)

display(kategori_count_all)

'Category Distribution per Province'

          PROVINCE                    Kategori  Jumlah Produk
0             Bali         Fashion & Aksesoris              7
1             Bali  Perawatan Diri & Kesehatan              1
2             Bali    Rumah Tangga & Furniture              1
4           Banten         Fashion & Aksesoris             75
10          Banten    Rumah Tangga & Furniture             26
..             ...                         ...            ...
58  Sumatera Utara         Fashion & Aksesoris              9
60  Sumatera Utara            Ibu, Bayi & Anak              8
62  Sumatera Utara    Rumah Tangga & Furniture              4
59  Sumatera Utara      Hobi, Seni, & Olahraga              1
61  Sumatera Utara            Otomotif & Mesin              1

[63 rows x 3 columns]